DROP TABLE IF EXISTS alumnos;
CREATE TABLE alumnos(
	id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT
    , nombre VARCHAR(255) NOT NULL
    , apellido VARCHAR(255) NOT NULL
	, usuario VARCHAR(20) NOT NULL UNIQUE
	, contrasena VARCHAR(255) NOT NULL
	, fecha_nacimiento DATE
    , fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
